version: '3.6'
services:
    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
            POSTGRES_DB: products
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - '5434:5432'
        volumes:
            - ./postgres_data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=root@admin.com
            - PGADMIN_DEFAULT_PASSWORD=root
        ports:
            - '5052:80'

networks:
    integrador_backend:
        driver: bridge
